// Generated by tools/gen-native-theme.mjs from core/ui/css - do not edit by hand.
// Regenerate with: node tools/gen-native-theme.mjs

#pragma once

#include <cstdint>

namespace soundshed::nano::theme
{
/// One theme's colours as 0xAARRGGBB, named after the web UI's CSS custom properties.
struct ThemeTokens
{
    std::uint32_t accent; // --color-accent
    std::uint32_t accentHover; // --color-accent-hover
    std::uint32_t accentDark; // --color-accent-dark
    std::uint32_t success; // --color-success
    std::uint32_t info; // --color-info
    std::uint32_t error; // --color-error
    std::uint32_t warning; // --color-warning
    std::uint32_t bgPrimary; // --bg-primary
    std::uint32_t bgSecondary; // --bg-secondary
    std::uint32_t bgTertiary; // --bg-tertiary
    std::uint32_t bgSurface; // --bg-surface
    std::uint32_t bgElevated; // --bg-elevated
    std::uint32_t bgPanel; // --bg-panel
    std::uint32_t bgCard; // --bg-card
    std::uint32_t bgInput; // --bg-input
    std::uint32_t bgHeader; // --bg-header-dark
    std::uint32_t bgFooter; // --bg-footer
    std::uint32_t textPrimary; // --text-primary
    std::uint32_t textSecondary; // --text-secondary
    std::uint32_t textTertiary; // --text-tertiary
    std::uint32_t textMuted; // --text-muted
    std::uint32_t textOnDark; // --text-dark-primary
    std::uint32_t borderLight; // --border-light
    std::uint32_t borderMedium; // --border-medium
    std::uint32_t borderStrong; // --border-strong
    std::uint32_t controlBg; // --control-bg
    std::uint32_t controlKnobBg; // --control-knob-bg
    std::uint32_t controlBorder; // --control-border
    std::uint32_t controlIndicator; // --control-indicator
    std::uint32_t knobRingStart; // --knob-ring-start
    std::uint32_t knobRingEnd; // --knob-ring-end
    std::uint32_t knobRingTrack; // --knob-ring-track
    std::uint32_t toggleBg; // --toggle-bg
};

inline constexpr ThemeTokens kLight {
    0xffb5521e, // accent
    0xffc9601f, // accentHover
    0xff964118, // accentDark
    0xff68b868, // success
    0xff6888a8, // info
    0xffc86868, // error
    0xffd63031, // warning
    0xfff9fafb, // bgPrimary
    0xffffffff, // bgSecondary
    0xfff3f4f6, // bgTertiary
    0xffffffff, // bgSurface
    0xffffffff, // bgElevated
    0xfff3f4f6, // bgPanel
    0xffffffff, // bgCard
    0xffffffff, // bgInput
    0xff3a3a40, // bgHeader
    0xffffffff, // bgFooter
    0xff111318, // textPrimary
    0xff4b5563, // textSecondary
    0xff6a6a78, // textTertiary
    0xff6a7280, // textMuted
    0xffe0e0f0, // textOnDark
    0xffe5e7eb, // borderLight
    0xffd1d5db, // borderMedium
    0xffbcc1cc, // borderStrong
    0xffffffff, // controlBg
    0xffe8eaef, // controlKnobBg
    0xffc8cad6, // controlBorder
    0xff5a5a6a, // controlIndicator
    0xffffffff, // knobRingStart
    0xff2ec868, // knobRingEnd
    0x2e000000, // knobRingTrack
    0xffb0b4c0, // toggleBg
};

inline constexpr ThemeTokens kDark {
    0xffff8850, // accent
    0xffff9860, // accentHover
    0xffe86838, // accentDark
    0xff68b868, // success
    0xff6888a8, // info
    0xffc86868, // error
    0xffd63031, // warning
    0xff111116, // bgPrimary
    0xff18181e, // bgSecondary
    0xff1e1e25, // bgTertiary
    0xff20202a, // bgSurface
    0xff26262e, // bgElevated
    0xff1c1c23, // bgPanel
    0xff22222a, // bgCard
    0xff1e1e26, // bgInput
    0xff0e0e13, // bgHeader
    0xff141419, // bgFooter
    0xffebebf4, // textPrimary
    0xffc8c8d8, // textSecondary
    0xffa0a0b4, // textTertiary
    0xff9fa0b8, // textMuted
    0xfff0f0f8, // textOnDark
    0xff2c2c38, // borderLight
    0xff262630, // borderMedium
    0xff1e1e28, // borderStrong
    0xff2e2e3a, // controlBg
    0xff2e2e3a, // controlKnobBg
    0xff46465a, // controlBorder
    0xffd0d0e0, // controlIndicator
    0xff292929, // knobRingStart
    0xff117c1e, // knobRingEnd
    0x12ffffff, // knobRingTrack
    0xff50505e, // toggleBg
};

inline constexpr ThemeTokens kClassic {
    0xfff0a010, // accent
    0xfff8b533, // accentHover
    0xffd88a00, // accentDark
    0xff6fae95, // success
    0xff6f9db5, // info
    0xffc86868, // error
    0xffd63031, // warning
    0xff2a1f15, // bgPrimary
    0xff3d2f25, // bgSecondary
    0xff4a403a, // bgTertiary
    0xff3d2f25, // bgSurface
    0xff4a403a, // bgElevated
    0xff3d2f25, // bgPanel
    0xff3d2f25, // bgCard
    0xff1f1815, // bgInput
    0xff2a1f15, // bgHeader
    0xff3d2f25, // bgFooter
    0xfff5f1e8, // textPrimary
    0xffe0dcd2, // textSecondary
    0xffc9c5bb, // textTertiary
    0xffb8ad9f, // textMuted
    0xfff5f1e8, // textOnDark
    0xff6b5f4f, // borderLight
    0xff5a5048, // borderMedium
    0xff4a403a, // borderStrong
    0xff4a403a, // controlBg
    0xff8a7a6a, // controlKnobBg
    0xff6b5f4f, // controlBorder
    0xfff5f1e8, // controlIndicator
    0xff5b3d21, // knobRingStart
    0xffb9c500, // knobRingEnd
    0x26fff4dc, // knobRingTrack
    0xff4a403a, // toggleBg
};

} // namespace soundshed::nano::theme
