#pragma once

#define GUITARFX_BRAND_COMPANY_STR "Soundshed"
#define GUITARFX_BRAND_PRODUCT_STR "GuitarFX"
#define GUITARFX_BRAND_COPYRIGHT_YEAR_STR "2025"
#define GUITARFX_BRAND_DOMAIN_STR "com.soundshed.guitarfx"
#define GUITARFX_BRAND_DISPLAY_STR GUITARFX_BRAND_COMPANY_STR " " GUITARFX_BRAND_PRODUCT_STR

#define PLUG_NAME GUITARFX_BRAND_PRODUCT_STR
#define PLUG_MFR GUITARFX_BRAND_COMPANY_STR
#define PLUG_VERSION_HEX 0x00040000
#define PLUG_VERSION_STR "0.4.0"
#define PLUG_UNIQUE_ID 'SGFX'
#define PLUG_MFR_ID 'SndS'
#define PLUG_URL_STR "https://soundshed.com"
#define PLUG_EMAIL_STR "support@soundshed.com"
#define PLUG_COPYRIGHT_STR "Copyright " GUITARFX_BRAND_COPYRIGHT_YEAR_STR " " GUITARFX_BRAND_COMPANY_STR

#define PLUG_CHANNEL_IO "1-1 2-2"

#define PLUG_LATENCY 0
#define PLUG_TYPE 0
#define PLUG_DOES_MIDI_IN 0
#define PLUG_DOES_MIDI_OUT 0
#define PLUG_DOES_MPE 0
#define PLUG_DOES_STATE_CHUNKS 1
#define PLUG_HAS_UI 1
#define PLUG_WIDTH 1880
#define PLUG_HEIGHT 1680
#define PLUG_MIN_WIDTH 640
#define PLUG_MAX_WIDTH 3840
#define PLUG_MIN_HEIGHT 480
#define PLUG_MAX_HEIGHT 2160
#define PLUG_FPS 60
#define PLUG_SHARED_RESOURCES 0

#define BUNDLE_NAME GUITARFX_BRAND_PRODUCT_STR
#define BUNDLE_MFR GUITARFX_BRAND_COMPANY_STR
#define BUNDLE_DOMAIN GUITARFX_BRAND_DOMAIN_STR

#define SHARED_RESOURCES_SUBPATH GUITARFX_BRAND_PRODUCT_STR

#define PLUG_BG_COLOR 0x202020FF

#define VST3_SUBCATEGORY "Fx"

#ifdef __cplusplus
namespace guitarfx::branding
{
inline constexpr const char* kCompany = GUITARFX_BRAND_COMPANY_STR;
inline constexpr const char* kProduct = GUITARFX_BRAND_PRODUCT_STR;
inline constexpr const char* kDisplay = GUITARFX_BRAND_DISPLAY_STR;
inline constexpr const char* kDomain = GUITARFX_BRAND_DOMAIN_STR;
}
#endif
