set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(NOT DEFINED CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER x86_64-linux-gnu-gcc CACHE FILEPATH "x64 Linux C compiler")
endif()

if(NOT DEFINED CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER x86_64-linux-gnu-g++ CACHE FILEPATH "x64 Linux C++ compiler")
endif()

if(DEFINED ENV{GUITARFX_LINUX_SYSROOT} AND NOT "$ENV{GUITARFX_LINUX_SYSROOT}" STREQUAL "")
    set(CMAKE_SYSROOT "$ENV{GUITARFX_LINUX_SYSROOT}" CACHE PATH "Linux target sysroot")
    list(APPEND CMAKE_FIND_ROOT_PATH "$ENV{GUITARFX_LINUX_SYSROOT}")
endif()

if(DEFINED ENV{GUITARFX_LINUX_PKG_CONFIG_SYSROOT_DIR} AND NOT "$ENV{GUITARFX_LINUX_PKG_CONFIG_SYSROOT_DIR}" STREQUAL "")
    set(ENV{PKG_CONFIG_SYSROOT_DIR} "$ENV{GUITARFX_LINUX_PKG_CONFIG_SYSROOT_DIR}")
endif()

if(DEFINED ENV{GUITARFX_LINUX_PKG_CONFIG_LIBDIR} AND NOT "$ENV{GUITARFX_LINUX_PKG_CONFIG_LIBDIR}" STREQUAL "")
    set(ENV{PKG_CONFIG_LIBDIR} "$ENV{GUITARFX_LINUX_PKG_CONFIG_LIBDIR}")
endif()

find_program(GUITARFX_X64_PKG_CONFIG_EXECUTABLE
    NAMES x86_64-linux-gnu-pkg-config pkg-config)

if(GUITARFX_X64_PKG_CONFIG_EXECUTABLE)
    set(PKG_CONFIG_EXECUTABLE "${GUITARFX_X64_PKG_CONFIG_EXECUTABLE}" CACHE FILEPATH "pkg-config for x64 Linux" FORCE)
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)