include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/GuitarfxWindowsArch.cmake")

function(guitarfx_detect_ipp)
    if(DEFINED GUITARFX_IPP_AVAILABLE)
        return()
    endif()

    set(_ipp_available OFF)
    set(_ipp_root "")
    set(_ipp_inc "")
    set(_ipp_lib "")
    set(_ipp_libs "")
    set(_ipp_macos OFF)

    if(WIN32)
        guitarfx_detect_windows_arch(_guitarfx_windows_arch)

        if(_guitarfx_windows_arch MATCHES "^(x64|amd64|x86_64)$")
            if(DEFINED IPP_ROOT AND IS_DIRECTORY "${IPP_ROOT}")
                set(_ipp_root "${IPP_ROOT}")
            elseif(DEFINED intelipp_static_win_x64_SOURCE_DIR AND IS_DIRECTORY "${intelipp_static_win_x64_SOURCE_DIR}")
                set(_ipp_root "${intelipp_static_win_x64_SOURCE_DIR}")
            elseif(DEFINED CPM_PACKAGE_intelipp_static_win_x64_SOURCE_DIR AND IS_DIRECTORY "${CPM_PACKAGE_intelipp_static_win_x64_SOURCE_DIR}")
                set(_ipp_root "${CPM_PACKAGE_intelipp_static_win_x64_SOURCE_DIR}")
            elseif(DEFINED ENV{USERPROFILE} AND EXISTS "$ENV{USERPROFILE}/.nuget/packages/intelipp.static.win-x64/2022.3.1.8")
                file(TO_CMAKE_PATH "$ENV{USERPROFILE}/.nuget/packages/intelipp.static.win-x64/2022.3.1.8" _ipp_root)
            endif()
        endif()

        if(NOT _ipp_root STREQUAL "")
            set(_ipp_inc "${_ipp_root}/build/native/include/ipp")
            set(_ipp_lib "${_ipp_root}/build/native/win-x64")
            set(_ipp_libs ippsmt ippcoremt ippimt ippcvmt ippvmmt)
            if(EXISTS "${_ipp_inc}/ipp.h" AND EXISTS "${_ipp_lib}/ippcoremt.lib" AND EXISTS "${_ipp_lib}/ippsmt.lib" AND EXISTS "${_ipp_lib}/ippimt.lib")
                set(_ipp_available ON)
            endif()
        endif()
    elseif(APPLE)
        if(CMAKE_OSX_ARCHITECTURES MATCHES "x86_64" OR
           (NOT CMAKE_OSX_ARCHITECTURES AND CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64"))
            include(FetchContent)
            FetchContent_Declare(ipp_include
                URL https://files.pythonhosted.org/packages/f0/a0/3b0329735b28f05cbb87ce86be09567a2ecdf9bcd92c50b05fd0a30b34b9/ipp_include-2021.9.1-py2.py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.whl
                URL_HASH SHA256=5d01a621a9ca758180dffac9677d37ad23759e3c606a376c4bc85adc79a86e6c)
            FetchContent_Declare(ipp_static
                URL https://files.pythonhosted.org/packages/fa/19/8b5d54390389b5a9910a111bc033cb0045dc2e1614745c2c98dc54061370/ipp_static-2021.9.1-py2.py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.whl
                URL_HASH SHA256=d0e1f6643c1e1cf64722dd57b71aaa2692e40406abcecc3c3d575c519326390f)
            FetchContent_MakeAvailable(ipp_include ipp_static)

            set(_ipp_root "${ipp_include_SOURCE_DIR}")
            set(_ipp_inc "${ipp_include_SOURCE_DIR}/ipp_include-2021.9.1.data/data/include")
            set(_ipp_lib "${ipp_static_SOURCE_DIR}/ipp_static-2021.9.1.data/data/lib")
            if(EXISTS "${_ipp_inc}/ipp.h")
                set(_ipp_available ON)
                set(_ipp_macos ON)
            endif()
        endif()
    elseif(UNIX)
        set(_ipp_root "/opt/intel/oneapi/ipp/latest")
        set(_ipp_inc "${_ipp_root}/include")
        set(_ipp_lib "${_ipp_root}/lib")
        set(_ipp_libs ipps ippcore ippi ippcv ippvm)
        if(EXISTS "${_ipp_inc}/ipp.h")
            set(_ipp_available ON)
        endif()
    endif()

    if(NOT _ipp_root STREQUAL "")
        set(IPP_ROOT "${_ipp_root}" CACHE PATH "Intel IPP root directory" FORCE)
        set(IPP_INC "${_ipp_inc}" CACHE PATH "Intel IPP include directory" FORCE)
        set(IPP_LIB "${_ipp_lib}" CACHE PATH "Intel IPP library directory" FORCE)
        set(IPP_LIBS "${_ipp_libs}" CACHE STRING "Intel IPP libraries" FORCE)
    endif()
    set(IPP_MACOS ${_ipp_macos} CACHE BOOL "Intel IPP requires x86_64-only link options" FORCE)
    set(GUITARFX_IPP_AVAILABLE ${_ipp_available} CACHE BOOL "Intel IPP is available for this configure" FORCE)

    if(_ipp_available)
        message(STATUS "Intel IPP available at ${_ipp_root}")
    else()
        message(STATUS "Intel IPP not available for this configure")
    endif()
endfunction()

function(guitarfx_enable_ipp_for_target target_name)
    guitarfx_detect_ipp()

    if(NOT GUITARFX_IPP_AVAILABLE)
        return()
    endif()
    if(NOT TARGET ${target_name})
        return()
    endif()

    get_target_property(_guitarfx_target_type ${target_name} TYPE)
    if(_guitarfx_target_type STREQUAL "INTERFACE_LIBRARY")
        set(_guitarfx_visibility INTERFACE)
    else()
        set(_guitarfx_visibility PUBLIC)
    endif()

    target_include_directories(${target_name} ${_guitarfx_visibility} "${IPP_INC}")

    if(IPP_MACOS)
        target_compile_options(${target_name} ${_guitarfx_visibility} "SHELL:-Xarch_x86_64 -DPAMPLEJUCE_IPP=1")
        target_link_options(${target_name} ${_guitarfx_visibility}
            "SHELL:-Xarch_x86_64 -Wl,-L${IPP_LIB},-lipps,-lippi,-lippcv,-lippvm,-lippcore")
        return()
    endif()

    if(NOT "${IPP_LIB}" STREQUAL "")
        target_link_directories(${target_name} ${_guitarfx_visibility} "${IPP_LIB}")
    endif()
    if(NOT "${IPP_LIBS}" STREQUAL "")
        target_link_libraries(${target_name} ${_guitarfx_visibility} ${IPP_LIBS})
    endif()
    target_compile_definitions(${target_name} ${_guitarfx_visibility} PAMPLEJUCE_IPP=1)
endfunction()
